### ISSUE TITLE
write out wrong keywords in setup.py

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#10]
Hi again,

would it be please possible to print out wrong flags for the setup.py script ? In this case below the "--type=Release" is wrong, and I didn't know that. (BTW, what flag is for the release buildup ?)

```
milias@login.grid.umb.sk:~/Work/qch/software/autocmake_devel/sec_quant_F90_autocmake/.python setup.py --fc=ifort --mkl=sequential --type=Release --int64 build_intel_i8
Usage:
  ./setup.py [options] [<builddir>]
  ./setup.py (-h | --help)
```

**Comment by bast** [comment]
Currently I handle build types like this:
```
[type]
docopt: --type=<TYPE> Set the CMake build type (debug, release, or relwithdeb) [default: release].
define: '-DCMAKE_BUILD_TYPE=%s' % arguments['--type']
```

I need to think about better input validation. We use
[docopt](http://docopt.org) for input parsing.

**Comment by bast** [comment]
We may consider always including the build type code in `setup.py`
since it is so common.

**Comment by miroi** [comment]
Well, the "--type=release" flag is somehow not working with setup; leaving it for now.
```
milias@login.grid.umb.sk:~/Work/qch/software/autocmake_devel/sec_quant_F90_autocmake/.python setup.py --fc=ifort --mkl=sequential --type=release   --int64 build_intel_i8
Usage:
  ./setup.py [options] [<builddir>]
  ./setup.py (-h | --help)
```

**Comment by bast** [comment]
The flag `--type` is now always generated, see [9018ad3](https://github.com/scisoft/autocmake/commit/9018ad347f6074bff6e5c20fd0b7a12417ed284c).
