### ISSUE TITLE
help to adapt update.py for own fork & branch

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#113]
On my fork I created the branch to develop new test, fc_build_info.

In update.py, though I changed the AUTOCMAKE_GITHUB_URL variable to point to my fork, and  replaced  *master* by the branch name, I can not assemble module because it's still pointing to the official scisoft repository.

Here is my modified update.py file, https://github.com/miroi/autocmake/blob/build_info/update.py

@bast , please what do I have to change in private update.py to get modules assembling running ? 

The problem seems to be here, https://github.com/miroi/autocmake/blob/build_info/update.py#L288 , where it sets wrong src=https://github.com/scisoft/autocmake/raw/master/modules/build_info/build_info_sub.cmake .
~~~
milias@login.grid.umb.sk:~/Work/qch/software/software_projects/autocmake_devel/autocmake_miroi/test/fc_build_info/
cmake/.python update.py  ..
- parsing autocmake.cfg
- assembling modules: [##############################] (4/4)ERROR: could not fetch //github.com/scisoft/autocmake/raw/master/modules/build_info/build_info_sub.cmake
milias@login.grid.umb.sk:~/Work/qch/software/software_projects/autocmake_devel/autocmake_miroi/test/fc_build_info/
cmake/.
~~

**Comment by bast** [comment]
The problem is this:
https://github.com/miroi/autocmake/blob/build_info/modules/build_info/build_info.cmake#L10-L11

Sorry, this is an undocumented feature to fetch files.

**Comment by miroi** [comment]
Thanks, this helped me.

Some documentation for developers, https://autocmake.readthedocs.org/en/latest/developers/faq.html , would help.

**Comment by bast** [comment]
I will document the `fetch` feature.
