### ISSUE TITLE
Write Git hash to setup.py and CMakeLists.txt

### ISSUE THREAD

**Issue by bast** [scisoft/autocmake#115]

**Comment by miroi** [comment]
Ah, good idea - we need to track the hash ("version") of the autocmake/autocmake-in-software.

And do you also plan to have the 'classic' versioning with a VERSION file  ?

**Comment by bast** [comment]
Yes we want to have versions following http://semver.org.
We will make it 1.0.0 once we release Autocmake (and create a release branch to support it).

**Comment by bast** [comment]
OK after some thought we will not write the hash to these files since it would complicate testing (require network). Rather we will create a file VERSION at `update.py --self` time.

**Comment by bast** [comment]
I am closing this. Once Autocmake gets a proper 1.0.0 version we will fetch that file.
