### ISSUE TITLE
adapt the testing so that it does not download anything

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#117]
Following discussion https://github.com/scisoft/autocmake/pull/116#issuecomment-138331373  we need to adapt the testing so that it does not download anything .

It would be much smarter to copy local files (from modules) than downloading/fetching them from external repos.

**Comment by bast** [comment]
Yes the testing should not need network. We then don't test the update from network, obviously, but that's OK since we will quickly notice when this one breaks in every day work.
