### ISSUE TITLE
Autocmake on Microsoft Windows 

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#12]
Would it be please possible to add the "--generator" flag for the setup.py script ?

With the DIRAC software, we are using the 'setup --generator="MinGW Makefiles" ....' on MS Windows platform together with the (GNU) MinGW64 compilers suite.

Best, M.

**Comment by bast** [comment]
I think this is a good idea. Would you like to contribute a patch for that?
You are in a better position to test such a patch.

**Comment by miroi** [comment]
Another connected issue with MS Windows is employing own CI service. According to Ivan Hrasko's (https://github.com/ihrasko) diploma thesis (DIRAC on MS Windows), there is the MS Windows CI service AppVeyor, http://www.appveyor.com/ . 

Can I prepare and add appveyor.yml script for this CI service ?

**Comment by bast** [comment]
I think this is a good suggestion but I would prefer this to first happen on a branch on your fork. Then, once Autocmake and the Appveyor CI integration stabilize a bit and we see it in action, we can integrate it to the main repo.

**Comment by miroi** [comment]
Fine;
so get it properly running on my fork and demonstrate it to the whole world, I have to place own buildup badges into https://github.com/miroi/autocmake/blob/master/README.md , right ?

**Comment by bast** [comment]
Yes but I would not place it on the master branch because this will make it difficult
for you to file pull requests.

**Comment by miroi** [comment]
Closing due to accepted https://github.com/scisoft/autocmake/pull/18 .
