### ISSUE TITLE
Compilers versions determination

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#120]
I am opening this issue to discuss how to implement the determination of compilers versions as was implemented in DIRAC by Ivan Hrasko ( @ihrasko ).

Should I create a subdirectory *modules/compilers_version* and put python script and a new cmake module there ?

Comments, hints & tips ?

**Comment by bast** [comment]
Is this something we should be programming ourselves? CMake now supports `CMAKE_<LANG>_COMPILER_VERSION`.

**Comment by miroi** [comment]
Ivan found that CMake does not determine Fortran version, so he programmed smart Python script for that purpose.

**Comment by bast** [comment]
I have just tested this on CMake 3.3.1 and it did correctly determine my Fortran version. When does this not work?

**Comment by miroi** [comment]
These are older CMake version, but allowed in previous DIRAC, where this feature is not working properly, so Ivan secured it with the dedicated Python script (which we praised in our referee reviews of his Master Thesis).

See 
https://gitlab.com/dirac/dirac/blob/miro/relcc-ff-operators/cmake/compilers/FindCompilerVersion.cmake

https://gitlab.com/dirac/dirac/blob/miro/relcc-ff-operators/cmake/compilers/GetCompilerVersion.py

**Comment by bast** [comment]
Well, I don't know what to say. If you want to implement it to support older CMake versions, go ahead.
Ivan's work was certainly needed and good. Personally, I rather like to install the latest CMake and use the built-in variables.

**Comment by bast** [comment]
I am closing this since this is not an Autocmake issue per se. With this I don't want to kill the discussion but the discussion should perhaps happen somewhere else.

**Comment by miroi** [comment]
Hi again,

I checked CMAKE_Fortran_COMPILER_VERSION with pgf90 - it does not detect it (CMake 2.8.12.2). CMake  detects GNU compilers versions, maybe they will add some more. Ivan's flexible Python script can handle all compilers.

The question is whether we should have this feature  in Autocmake. What's your opinion, Rado ( @bast ) ?

**Comment by bast** [comment]
Have you tried with more recent CMake? If you need it, implement it. If it is useful for you it typically will be useful for others and eventually it can grown into an official module. Don't write it for Autocmake, write it for you.

**Comment by miroi** [comment]
Newer CMake does not determine the pgf90 Fortran compiler version properly:
~~~
milias@login.grid.umb.sk:~/Work/qch/software/software_projects/autocmake_devel/autocmake_miroi/test/fc/.python setup.py --fc=pgf90 --cmake-executable=/home/milias/bin/cmake/cmake-3.3.0-Linux-x86_64/bin/cmake  build_pgf90_cmake
FC=pgf90 /home/milias/bin/cmake/cmake-3.3.0-Linux-x86_64/bin/cmake -DEXTRA_FCFLAGS="''" -DENABLE_STATIC_LINKING=False -DCMAKE_BUILD_TYPE=release -G "Unix Makefiles" /home/milias/Work/qch/software/software_projects/autocmake_devel/autocmake_miroi/test/fc

CMAKE_Fortran_COMPILER_VERSION=1.1
milias@login.grid.umb.sk:~/Work/qch/software/software_projects/autocmake_devel/autocmake_miroi/test/fc/.pgf90 -V

pgf90 13.10-0 64-bit target on x86-64 Linux -tp nehalem
~~~

Anyhow, I wanted to restore the compilers versions determination for DIRAC,  what is now possible only through the autocmake.

I believe this feature (for which we already have Ivan's Python script) will be useful for other scientific software, where they need to check against minimal compilers (Fortram,C,C++) versions.

**Comment by bast** [comment]
OK but I want to precise that it is possible to use Autocmake without writing an Autocmake module.
Everything that is possible with "pure" CMake will also run on Autocmake.

**Comment by miroi** [comment]
Fine;  in order not to overload autocmake,  this feature could be planted among DIRAC custom modules. 

Similarly, also the discussed build_info.h feature (https://github.com/scisoft/autocmake/issues/110) could be in the same custom modules directory. 

Is it good solution ?

**Comment by bast** [comment]
It is generally a good strategy to "grow" modules as custom modules until they become of general interest and then become core modules.

**Comment by miroi** [comment]
Right, it's already in the manual, https://autocmake.readthedocs.org/en/latest/developers/faq.html#autocmake-does-not-do-feature-x-i-really-need-feature-x-and-a-setup-py-flag-x .
