### ISSUE TITLE
Boost tests are broken

### ISSUE THREAD

**Issue by bast** [scisoft/autocmake#123]
Known issue. Working on it.

**Comment by bast** [comment]
@robertodr which line is it again that I would need to hardcode to make the Boost tests pass?

**Comment by robertodr** [comment]
Hi Radovan, the problem was with this line:

    source: ../../../modules/boost/boost.cmake

as the target was an out-of-source. With the current design I see a different failure:

    make[2]: *** No rule to make target '/home/roberto/Workspace/autocmake/modules/boost/boost_1_59_0.zip', needed by 'boost/boost.unpacked'.  Stop.

And this comes about because the `fetch` command in `autocmake.cfg` correctly fetches the archive into the test directory own `cmake/downloaded` directory.

**Comment by bast** [comment]
I am a bit confused about the combination of "problem" and "correctly" :-) Where do you think is the problem that we need to fix? What is wrong?

**Comment by robertodr** [comment]
OK, sorry for the confusion... In `boost_header_only/cmake/autocmake.cfg` we have:

    [custom]
    source: custom/boost_version-components.cmake

    [boost]
    source: ../../../modules/boost/boost.cmake
    fetch: http://sourceforge.net/projects/boost/files/boost/1.48.0/boost_1_48_0.zip

The .zip file is fetched and saved into `downloaded` (as it's supposed to do) The failure comes from the `boost.cmake` script looking for the .zip file, not in the current tree, but into the autocmake project tree, i.e. in the `modules/boost` directory.

**Comment by bast** [comment]
After looking at it I am thinking that it could be better to not use the fetch command for the zip file. This is because the CMake module cannot live without it. I think it would be better to define the desired Boost major/minor/patch, then to fetch the zip by the CMake module which would make the module more black box (as it used to be, then possibly reopening some other problems with paths?).
The Boost major/minor/patch could then be modified by autocmake.cfg.
Perhaps this approach is problematic and in this case please refresh my memory why it is problematic.

**Comment by robertodr** [comment]
The problem with this approach was that fetching happens at build time. This is a problem when no internet connection is available. 
The current approach keeps a copy of the archive in the bootstrapped repository.

**Comment by bast** [comment]
OK I see - thanks. I need to think more about how to do it without making it complicated.

**Comment by bast** [comment]
It's not so easy to make this fit into the way things are set up. I want to avoid that the Boost version is set in several places (now in fact it is) and to complicate the `fetch` behavior. Probably the easiest and cleanest from the Autocmake perspective would be to fetch at build time but I see the downside of it. For the moment I will deactivate the Boost tests so that we don't introduce other errors in the meantime.

**Comment by robertodr** [comment]
Yes, that seems like the right solution at this point. Would it be possible to have docopt directives in the `custom/boost_version-components.cmake` file?

**Comment by bast** [comment]
Sorry for answering so late. I need to write something about the motivation behind the current
settings and apologize that these are mostly undocumented.

The idea was that "source" would fetch and "parse" and include but "fetch" would only fetch and not parse and not include. This can of course be changed.

Then the idea of "autocmake.cfg configuration" was that if one would copy-paste it from the web
or the source file and add a "config: custom", in front of it, it should do the same and it should work.
The idea is to minimize surprises. Coming back to Boost, it could be a bit surprising to take the documented "autocmake.cfg configuration" and realize that it does not work because it is not sufficient.
So my idea was that modules can be extended or reset but on their own they should also work.
This all hints that the downloading should happen in the CMake module and not in `autocmake.cfg`.
This is of course not written in stone and is debatable. It's just what I initially thought:
Make it customizeable, make it resetable, but also make it work on its own.

The issue is that we want to allow the user to specify the version from "outside" IOW in `autocmake.cfg`.
This is easy to do if the tarball is fetched deep down in CMake at configure or build time with the
disadvantage of requiring network at these times. The alternative would be to "sed" a fetch command
which is defined in the CMake module documentation. This is currently not possible but could be implemented.

The coding is not difficult. My question is what is the better design. I am not sure yet myself and will
welcome any input/feedback.

**Comment by bast** [comment]
Another thing that I didn't like about the current solution is that you need to edit versions two places.
So what we want is this:
- Edit in one place.
- Make the module work also without `autocmake.cfg` customizations.
- But make such customizations possible.
- Ideally fetch at "autocmake time".

These are the specs. The challenge is to make this happen without making a Kafka design.

**Comment by robertodr** [comment]
Thanks for the explanation! Yes, I agree that the current design is flawed. I was basically forcing my way into the current design of autocmake.
As we discussed already, any fetching should happen, IMO, at "autocmake time", so that the CMake infrastructure maintainer(s) has(have) full control.
What I had originally envisioned for the Boost module would lead to the following syntax in `autocmake.cfg`:

    [boost]
    source: 
    min_required_version: 
    required_components: 

Where:

* `source` Points to the boost.cmake module, which fetches the additional build-up macros.
* `min_required_version` Fetches boost_MAJOR_MINOR_SUBMINOR.zip at "autocmake time" from sourceforge
* `required_components` Options: none (header only), all (all libraries are built), a comma-separated selection of libraries to be built (timer, chrono, system, filesystem) If left empty all libraries are built

The question is, how easily can the `autocmake.cfg` syntax be extended?

**Comment by bast** [comment]
We have achieved configure-time customization using interpolations. Issue with broken tests is followed upon in #141. Closing this one.
