### ISSUE TITLE
test for mpi_int64 ?

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#124]
Shouldn't we test MPI with the integer*8 variables ? 

In DIRAC, this is yet unsolved issue , see https://gitlab.com/dirac/dirac/issues/41 One has to treat  all MPI calling parameters properly in the ILP64  mode.

**Comment by bast** [comment]
[Please don't refer to non-public links in this public discussion]

I think we should not. For the following reasons:

1) MPI with 64-bit integers in my opinion currently cannot reliably be done.

2) For the above reason, MPI with 64-bit integers in my opinion should not be done (this way).

3) Every test has a cost and a benefit. The cost is not only in writing and running the test but also in maintaining and fixing it. The benefit is roughly speaking code coverage. In this case the cost would be huge and the benefit for Autocmake close to zero. In this case we would not test Autocmake but rather the compilation and robustness of MPI itself. I understand that there would be benefit for other projects but then it should be tested outside Autocmake.

**Comment by miroi** [comment]
Thanks for your statement; closing this issue.
