### ISSUE TITLE
CMake printouts of git_info ?

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#129]
Hi,

shouldn't we have some CMake printouts (message ...) from the **git_info** module ?

https://github.com/scisoft/autocmake/blob/master/modules/git_info/git_info_sub.cmake

Like previously in DIRAC, see for example https://testboard.org/cdash/buildSummary.php?buildid=21035 , we printed out git status variables to ease CDash tests control.

**Comment by bast** [comment]
I think this would not harm.

**Comment by miroi** [comment]
Well, after thinking a little more I am against printing from git_info. 

Why ?  The cmake output must be consistent and esthetic, and **git_info** data should go smoothly after build_info printout. See for example https://testboard.org/cdash/buildSummary.php?buildid=32894 (though git_info is not printed out there).

Comments ?

**Comment by bast** [comment]
Not having the printout is fine for me, too. Closing the issue then.
