### ISSUE TITLE
Split math library into separate modules

### ISSUE THREAD

**Issue by bast** [scisoft/autocmake#133]
We are in the process of splitting `math_libs.cmake` into individual modules.

Preliminary list:
- blas
- cblas
- lapack
- lapacke
- essl
- acml
- openblas
- atlas
- mkl

The redesign will allow to switch to static linking by the caller and therefore explicit static
linking will not be done in the math library modules but it will become optional "on the outside".
Therefore also corresponding tests for static math library linking will be removed.

**Comment by miroi** [comment]
Hi Rado,

I suggest more natural splitting of *math_libs.cmake*, according to math library providers:

SYSTEM_NATIVE; OpenBLAS, MKL, ESSL, ATLAS, ACML.

Eeach one should cover both Fortran and C blas and lapack.

**Comment by bast** [comment]
Well I am not sure it is so natural in fact. They don't provide the same functionality. And some codes only need BLAS and do not need LAPACK. MKL provides both. Then there is CBLAS and LAPACKE, where does that fit in? Then on Mac there is the Accelerate framework (my plan is to also introduce `--accelerate`).

**Comment by miroi** [comment]
OK, then go ahead with your ideas.

**Comment by bast** [comment]
The aim of the reorg is "explicit is better than implicit".

**Comment by miroi** [comment]
Rado, one new feature would be helpful: combining several math libraries.

For example, the OpenBLAS has no dgesv (routine from LAPACK), would be good to have following SYSTEM_NATIVE or ATLAS lapack library as second (third etc) among linking flags.

**Comment by bast** [comment]
This will be unproblematic in the upcoming implementation.

**Comment by miroi** [comment]
Good; looking forward to new math_libs CMake macros implementation.  

Than I will check it with the mathlibs-tester, both with Fortran and C.

**Comment by bast** [comment]
Process is ongoing. Will close this issue to keep better overview.
