### ISSUE TITLE
Make static linking a thin external plugin instead of implementing and testing it deep down in the code

### ISSUE THREAD

**Issue by bast** [scisoft/autocmake#134]
With the redesign of the math library modules #133, Autocmake will allow to toggle static linking by the caller using a thin layer. Basically it will be possible to do this with one single pluggable module.
Since static linking is notoriously difficult to implement in a portable way, Autocmake will
stop supporting and testing it directly. However, Autocmake core modules will be designed in such
a way to enable switching to static linking by the caller. Another possibility is to fork off an "autocmake-static" repo or branch.

**Comment by bast** [comment]
@miroi after thinking about it for a long time I believe that implementing static linking by the caller is the right way to go. Let me know if you have questions. My aim is that we allow it and make it easy but not support the code for it directly. See also #133.

**Comment by miroi** [comment]
Good idea; mixing static linking flags into autocmake math_libs macros brings complications.

In the planned implementation we should provide than enough examples of static linking with/without math libs; including C language.

**Comment by bast** [comment]
I agree. Static linking is useful and important but it is a special case. I am now convinced that a good solution for us will be an outer shell implementing this. It will become a contributed module. And I think we should test it outside Autocmake.
