### ISSUE TITLE
Deactivated test_cxx_lapacke fails on Travis

### ISSUE THREAD

**Issue by bast** [scisoft/autocmake#137]
Cannot find LAPACKE there. Works on my Linux box.

**Comment by miroi** [comment]
Hi Rado,

i) maybe this (debian) package would help, https://packages.debian.org/sid/s390x/liblapacke-dev/filelist

ii) in the case of packages conflicting  (I met one case) on travis-CI I would introduce second CI service, with different configuration of packages.

**Comment by bast** [comment]
Thanks for the tip on the deb package. And I don't want to introduce other CI services at this time since this will increase maintenance. I am so far very happy with what we have.

**Comment by bast** [comment]
Waiting for the package to be whitelisted: https://github.com/travis-ci/apt-package-whitelist/issues/1399
