### ISSUE TITLE
suppress warning of unused MATH_LIB_SEARCH_ORDER

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#138]
Hi @bast ,

when blas=off+lapack=off, the empty MATH_LIB_SEARCH_ORDER variable spurs warning, which is interpreted as build interruption  for CircleCI: https://circleci.com/gh/miroi/DIRAC/296

Could be variable MATH_LIB_SEARCH_ORDER be set to some initial value to suppress this warning ?

~~~
CMake Warning:
  Manually-specified variables were not used by the project:


MATH_LIB_SEARCH_ORDER
~~~

**Comment by bast** [comment]
The big monolithic `math_libs.cmake` will soon disappear and with it `MATH_LIB_SEARCH_ORDER`.
Personally I will not do any more work on `math_libs.cmake` but feel free to set it to something.
Closing this issue.

**Comment by miroi** [comment]
Fine, I am not interested in math_libs.cmake improvement either.
