### ISSUE TITLE
test_boost_header_only tries to use wrong include directory

### ISSUE THREAD

**Issue by bast** [scisoft/autocmake#141]
test_boost_header_only fails because it does not use the include
directory in the extracted tarball but rather tries to use the system-wide
Boost installation include path. Therefore this test can pass on the local
machine (it passes on my laptop). @robertodr

**Comment by bast** [comment]
Solved the failing test. Happy for the moment. Closing.

**Comment by robertodr** [comment]
I gave it a try this afternoon and came to the same conclusion. I wasn't unfortunately able to do more... Great that you fixed it, thanks!

**Comment by bast** [comment]
Still the test is strange. I think it downloads the Boost tarball. Working on it.

**Comment by bast** [comment]
Ah it always downloads the tarball by the nature of the Boost module.

**Comment by robertodr** [comment]
Might there be a way to cache it? Maybe you could have it on the repository and "download" it from there? Sure it would enlarge the repo a bit...
