### ISSUE TITLE
test_boost_libs takes too long

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#145]
The **test/test.py::test_boost_libs** takes too long. Isn't there a way to make it faster ?

**Comment by bast** [comment]
Can we do something about it @robertodr?
We could have a minimum test set and an extended test set
because it really takes long at the moment.

**Comment by robertodr** [comment]
I guess it's so slow because it downloads the Boost archive.
A possible solution would be to have a copy of the archive available on the repo.

**Comment by bast** [comment]
If it's just the downloading we could try to group the tests with a common fixture.

**Comment by bast** [comment]
The problem is we download it 4 times. Do we actually compile it? Can the tests be collapsed into one? It is ultra slow. Also there is come CMake code for BUILD_CUSTOM_BOOST which is never used. Also there is some code complication of the chrono stuff. But also that is not really used inside the tests so could be removed.

**Comment by robertodr** [comment]
They can definitely be collapsed into one. I had honestly not thought that it could be such a showstopper ;) Can you point me to the unused `BUILD_CUSTOM_BOOST` code? Might be a leftover or a bug. I think it is enough to just Boost.MPI and Boost.Python libs, possibly together. They are the trickier to build. I would however leave the header-only test as an autonomous test.

**Comment by bast** [comment]
I think it would be good to test Python and MPI together for the sake of total test time.
So perhaps we can have one `boost` test and one `boost_headers` test.
The leftovers are for instance here:
https://github.com/scisoft/autocmake/blob/master/test/boost_mpi_libs/src/CMakeLists.txt#L3-L5

**Comment by robertodr** [comment]
OK. I'll take care of streamlining the tests on my fork and file a pull request. Those lines are not IMO a leftover, a build with -jN would fail without.

**Comment by bast** [comment]
OK then I misunderstood the lines - sorry.

**Comment by robertodr** [comment]
I'll add a comment in the Boost module documentation, to clarify it also for the users.
