### ISSUE TITLE
restore "static" tests

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#146]
Hi Rado,

would yoy agree with restoring some *static* tests, which were in previous autocmake version, in the new autocmake manner ?

**Comment by bast** [comment]
Currently I don't want to support static linking in the Autocmake core. I recommend to grow and test such a module outside Autocmake and incorporate it later. If we do things right it should just become a thin plug-in.

**Comment by bast** [comment]
Closing this issue but consider discussing this on http://autocmake.readthedocs.org/en/latest/general/help.html
