### ISSUE TITLE
Tests covering more functionalities

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#16]
Greetings,

while adapting autocmake for Windows I see need to have more complex tests, what means tests covering all possible Python/CMake functionalities of the autocmake project.

For example, I would welcome all possible entries into test/fc and test/cc autocmake.cfg files. This is closely related to modifying tests to include math libs (blas/lapack), parallel compilation, Fortran-C-C++ languge mixing etc.

The more autocmake's functionalities we test, the better for us.

**Comment by bast** [comment]
You are perfectly right, we need more tests.
However a tests should ideally test one thing and one thing only
in the spirit of unit tests. Later we may introduce combination tests.
The reason why there are only few tests at this moment is
that I was not sure (and still am not sure) about all aspects
of the API and first wanted to stabilize the API before introducing
many tests which use the API.

**Comment by miroi** [comment]
IMO, as long as is autocmake employed in "bigger", more complex projects, we should consequently include more testing. 

For example, when autocmake-for-DIRAC is using math libs detection, we are supposed to have one (simple) test for math detection.

**Comment by bast** [comment]
Absolutely.

**Comment by miroi** [comment]
Hi,

as the next simple test, I am suggesting a *fc_openblas* test , where simple a Fortran code would call some  BLAS routine located in the famous OpenBLAS library. 

The reason for OpenBLAS is that it's parallel and is availalble also for MS Windows (we have it in DIRAC, see https://testboard.org/cdash/buildSummary.php?buildid=16874).  Unfortunately, there is no GNU */usr/lib/libblas* equivalent on MS Windows.

**Comment by bast** [comment]
A good idea but the math module will go through at least one more iteration so expect API changes.

**Comment by bast** [comment]
I am closing this issue because it is a bit too diffuse. But it is of course a good point
and will be pursued.

**Comment by miroi** [comment]
Hi, 

could I please get green light for implementing the https://github.com/scisoft/autocmake/issues/16#issuecomment-116199678 ?

**Comment by bast** [comment]
More tests are always welcome!
