### ISSUE TITLE
Too many tests broken or deactivated on Windows

### ISSUE THREAD

**Issue by bast** [scisoft/autocmake#167]
@miroi  I am considering dropping automated testing on Appveyor because many of the corresponding tests are broken or deactivated. Nobody seems to have time or means to work on it. I don't see the value of such tests. What do you think?

**Comment by miroi** [comment]
As long as autocmake is beeing used with MS Windows, let us keep the tests.

Currently https://ci.appveyor.com/project/bast/autocmake tests are not even starting due to missing git...

**Comment by bast** [comment]
But what is the value of keeping them?

**Comment by miroi** [comment]
The value of (Windows working) tests is that they serve as working examples, which can be adapted for users purposes.

**Comment by bast** [comment]
Then they should not be tests but move to the documentation, right?

**Comment by bast** [comment]
And I don't think they serve as working examples because they are not working.

**Comment by bast** [comment]
Just to be clear I am not suggesting that we should stop supporting Windows. Python is cross-platform and CMake is cross-platform so Autocmake is cross-platform. I am just suggesting that we should stop the testing since it does not serve us anything. Many tests are deactivated and many active tests are broken. I don't see any value in that. I really appreciate your work on Windows integration and we should not stop this. I just think that we should test only on Linux and Mac for the moment. This is because I have no way to develop and test on Windows myself and you are busy too. We should focus our efforts. We should continue supporting Windows via issues. If there are problems, then we will know via issues.

**Comment by bast** [comment]
Miro, I think I will get rid of the automated Windows tests but if you like you can maintain a fork which focuses on Windows tests. However, I want to keep supporting Windows via issues. I believe with this we will be able to move faster while keeping portability.

**Comment by miroi** [comment]
Go ahead - I created own branch for supporting Windows, https://github.com/miroi/autocmake/tree/windows_supp .
