### ISSUE TITLE
Windows wget alternative 

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#17]
There is no wget command on MS Windows. Fortunately, there the https://pypi.python.org/pypi/wget project, so it become easy to download file:

~~~
pip install wget
python -m wget https://github.com/miroi/autocmake/raw/master/update.py
~~~

Would it be OK to use this scheme for autocmake on MS Windows ?

**Comment by bast** [comment]
You mean in the tests?

**Comment by miroi** [comment]
Yes, in tests; and in general recommend users to use pypi/wget on MS Windows.

**Comment by bast** [comment]
I want to avoid introducing additional dependencies unless
there is no other way. We can replace "wget" using urllib like we do in `update.py`.
But there is no problem recommending Windows users to "wget" using
the Python wget module.

**Comment by miroi** [comment]
Fine; in between I turned to Python wget. But later we may switch to the platform universal "urllib".

I am leaving this issue open till the final "wget" replacement.

**Comment by miroi** [comment]
Hi again,

woud it be please possible to extend documentation http://autocmake.readthedocs.org/en/latest/developers/bootstrap.html#bootstrapping-autocmake with this Windows download alternative ? 

There is not wget in Windowds by default, one uses the builtin PowersShell solution:

~~~
PS C:\Users\milias\Documents\work\autocmake-devel\autocmake\test\fc_blas\cmake> Invoke-WebRequest https://github.com/scisoft/autocmake/raw/master/update.py -OutFile update.py
~~~

**Comment by bast** [comment]
Sure, no problem. Please do that as PR.
