### ISSUE TITLE
URL of update.py in one place ?

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#21]
Greetings,

the URL for downloading the *update.py* , https://github.com/scisoft/autocmake/raw/master/update.py , are at four different places in autocmake:
* update.py
* test/test.py
* test/fc/cmake/autocmake.cfg
* test/cxx/cmake/autocmake.cfg

All these URLs have to be modified in when switching to autocmake forks, for example to https://github.com/miroi/autocmake/raw/master/update.py .

Could we have only one place in the code with this important URL ? The best solution would be  separate file (I don't know if it would work for autocmake.cfg).

**Comment by bast** [comment]
I agree that the current testing is annoying. I will change it such that it only
tests local files and will not fetch anything from the web. The current solution
is against "test first, push then".
