### ISSUE TITLE
deleting of tests build/ directories 

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#27]
Hi,

when repeating the tests 
~~~
py.test -v test/test.py
~~~

developers would be glad to have build/ directories deleted so that each run of test.py creates fresh builds.

**Comment by bast** [comment]
Good point. Probably we should run the entire test set in a temporary directory using
tempfile module. This would be safer but could complicate inspection. I am afraid of scripts
that automatically delete directories.
