### ISSUE TITLE
If setup.py fails to configure, it should print the reason to stderr

### ISSUE THREAD

**Issue by bast** [scisoft/autocmake#28]
Example: https://travis-ci.org/miroi/autocmake/builds/70649300

**Comment by bast** [comment]
Example: https://travis-ci.org/miroi/autocmake/builds/70649300

**Comment by miroi** [comment]
Yes, this is very much wanted. For example, here https://travis-ci.org/miroi/autocmake/builds/70649300  :

~~~
>       os.chdir(os.path.join(HERE, name, 'build'))
E       OSError: [Errno 2] No such file or directory: '/home/travis/build/miroi/autocmake/test/fc_openblas/build'
~~~

we need to know why the generated setup.py script failed (as there is no build directory) - and this is by getting the stderr stream.
