### ISSUE TITLE
Minimal Python version for update.py

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#3]
Hi,

Ad: https://github.com/scisoft/autocmake/blob/master/update.py#L8

would it be please possible to add the detection of a minimal Python version  ?

milias@login.grid.umb.sk:~/Work/qch/software/relat_rad_atomic_ihfscc/automake_ihfscc/cmake/python update.py --self
Traceback (most recent call last):
  File "update.py", line 8, in <module>
    if sys.version_info.major > 2:
AttributeError: 'tuple' object has no attribute 'major'
milias@login.grid.umb.sk:~/Work/qch/software/relat_rad_atomic_ihfscc/automake_ihfscc/cmake/.python --version
Python 2.6.6

**Comment by miroi** [comment]
Well, all powerfull clusters I am using have Python 2.6.6. Folks, we need adapt the update.py script for lower versions of Python.

**Comment by bast** [comment]
I have nothing against supporting a broader spectrum of versions
and will try to make this more general and/or accept corresponding
changes. On the other hand I do not think that it is important that ``update.py``
runs on all clusters since this script is not used to build a project.
It is only used to bootstrap a new project or to update the CMake infrastructure
files and both can be done on another machine (your laptop) with
a more recent Python.

**Comment by miroi** [comment]
Hi again,

so I moved to another machine with Python 2.7.6, and got another problem:

ilias@frpd2.pd.uniza.sk:~/Work/qch/qch_software/autocmake_ihfscc/cmake/.ls
autocmake.cfg  lib/  modules/  update.py

ilias@frpd2.pd.uniza.sk:~/Work/qch/qch_software/autocmake_ihfscc/cmake/.python -V
Python 2.7.9
ilias@frpd2.pd.uniza.sk:~/Work/qch/qch_software/autocmake_ihfscc/cmake/.python update.py ..
- parsing autocmake.cfg
Traceback (most recent call last):
  File "update.py", line 295, in <module>
    main(sys.argv)
  File "update.py", line 276, in main
    list_of_modules = fetch_modules(config, module_directory='modules')
  File "update.py", line 198, in fetch_modules
    print_progress_bar(text='- fetching modules:', done=0, total=n, width=30)
  File "update.py", line 47, in print_progress_bar
    n = int(float(width)*float(done)/float(total))
ZeroDivisionError: float division by zero
ilias@frpd2.pd.uniza.sk:~/Work/qch/qch_software/autocmake_ihfscc/cmake/.

The modified automake.cfg looks like:
# uncomment and set project name
[project]
name: Atomic-IHFSCC

Any help, please ?

**Comment by bast** [comment]
I have edited your comment and marked code blocks as such.
It greatly improves readability.

**Comment by bast** [comment]
OK here you have found a bug for projects which have no modules. This is independent
of the Python version. I will fix this one.

**Comment by bast** [comment]
The division by zero problem has been fixed in [8c38f35](https://github.com/scisoft/autocmake/commit/8c38f351674c99d00f4850329ab9589bed63340c).

**Comment by miroi** [comment]
Fine, 

got it working:
```
ilias@frpd2.pd.uniza.sk:~/Work/qch/qch_software/autocmake_ihfscc/cmake/.python update.py ..
- parsing autocmake.cfg
- generating CMakeLists.txt
- generating setup.py
```

now  next step is glue some project into ready autocmake infrastructure.

**Comment by bast** [comment]
The documentation is still in an early stage but you can check out the projects
that use Autocmake for inspiration and starting pointers.

**Comment by miroi** [comment]
Thanks, wooorks on my clusters :+1:  !

```
milias@login.grid.umb.sk:~/Work/qch/software/autocmake_devel/bootstrapping_autocmake/cmake/.python update.py --self
- fetching lib/config.py
- fetching lib/docopt.py
- fetching update.py
milias@login.grid.umb.sk:~/Work/qch/software/autocmake_devel/bootstrapping_autocmake/cmake/.python update.py ..
- parsing autocmake.cfg
- generating CMakeLists.txt
- generating setup.py
milias@login.grid.umb.sk:~/Work/qch/software/autocmake_devel/bootstrapping_autocmake/cmake/.python -V         
Python 2.6.6
```
