### ISSUE TITLE
Test fc_blas fails

### ISSUE THREAD

**Issue by bast** [scisoft/autocmake#33]
I doubt it ever properly worked on Travis.
Previously it passed trivially until [4d0784d](https://github.com/scisoft/autocmake/commit/4d0784dbd9e975991b9ab2bad659e926b741b363).

**Comment by bast** [comment]
Could you please have a look at this @miroi ? The test works
locally but fails on Travis.

**Comment by miroi** [comment]
https://github.com/scisoft/autocmake/commit/4d0784dbd9e975991b9ab2bad659e926b741b363

**Comment by bast** [comment]
Please see my comments in [4d0784d](https://github.com/scisoft/autocmake/commit/4d0784dbd9e975991b9ab2bad659e926b741b363).
With this I doubt the test ever worked for the right reason on Travis.

**Comment by miroi** [comment]
This is strange:
https://travis-ci.org/miroi/autocmake/builds/71224638

For some reasons travis does not detect string in stdout....
~~~
>           assert 'dgemm test ok' in stdout
E           assert 'dgemm test ok' in ''
~~~
Maybe I find a solution.

**Comment by bast** [comment]
I think there is simply no stdout.

**Comment by miroi** [comment]
Whiel playing with 
https://github.com/miroi/autocmake/blob/fix_travis/test/fc_blas/src/example.f90

The problem seems to appear  around commands "allocate - dgemm - deallocate", see https://travis-ci.org/miroi/autocmake/builds/71227409

Maybe dynamical allocation not permitted on travis-ci ?

**Comment by miroi** [comment]
Well, I have to instert stderr catchers, both from setup.py and example.f90. 

Stderr catching is urgently needed for cases as this one.

**Comment by bast** [comment]
Travis certainly allows dynamic allocation. But here we launch the code via a subprocess.
It could be that Travis blocks dynamic allocation for subprocesses to prevent fork-bombing the system.
We don't need dynamic allocation for this test - let's go with static arrays.

**Comment by miroi** [comment]
Static arrays are not working either. Plus missing stderr printout from example.f90/setup.py in the test.py script is making difficult to determine the exact cause of travis-ci test failure.

**Comment by miroi** [comment]
Static arrays are not the problem - https://travis-ci.org/miroi/autocmake/builds/71233486 .

Problem is own DGEMM calling, https://travis-ci.org/miroi/autocmake/builds/71234385 .

I don't see the stderr from the fortran executable. How to implement stderr catching into test.py ? I need it urgently. Without seeing all stderrs the development is pain.

**Comment by miroi** [comment]
Well, here: https://pytest.org/latest/capture.html 

Please give me, @bast, green light to implement it into test.py.

**Comment by bast** [comment]
Hi Miro, you don't need my permission. "Just Do It". That's the beauty of open source
and distributed version control: you can do anything you like and all improvements
will be incorporated.

**Comment by miroi** [comment]
Could we please close this issue ? The test is working now.

**Comment by bast** [comment]
Sure! Closing.
