### ISSUE TITLE
Wanted comprehensive stderr catcher in test.py

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#36]
According to the permission, https://github.com/scisoft/autocmake/issues/33#issuecomment-122101327 , 
we are in need of comprehensive (complex) stderr catcher in test.py which shows up all errors stream - from the test executable, from the setup.py script and also from the test.py script.

Currently the test.py's assert Python function does not point the exact source of failure. This is wanted especially with CI services, where we have no direct access to testing machines and we are left with reading available stderr  stream.

(Probably this function can be helpfull,  https://pytest.org/latest/capture.html , but one has to check it.)

**Comment by bast** [comment]
Hi Miro, I agree that this would be useful to have.

**Comment by miroi** [comment]
Well, I played with 'hurting' codes (executable, CMakeFiles.txt) and see that the stderr is automatically flushed out (in travis-ci) any time when an error happens

See for example https://travis-ci.org/miroi/autocmake/builds/71543111 .

So the problem  remains  when there is no stderr (formally all is right) and the stdout does not contain wanted string for test.py's assert. What to do in such cases ? We must do programming in a way to provide stderr flushout in crucial cases.

Leaving this issue open to explore it little more.

**Comment by bast** [comment]
Please create a simple example that demonstrates the problem. Otherwise
please close the issue.

**Comment by miroi** [comment]
So far I haven't found 'working' example, closing this issue.
