### ISSUE TITLE
More (free) CI services employed for testing ?

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#37]
Hi again,

there are some more free CI services we are currently using in DIRAC;

The issue is to have more (different) machines employed for testing of autocmake's content.

Machines with older vs newer architecture, modern vs old-fashioned, virtual vs native, different Linux distros etc. - all these factors will have some impact on the testing commands:
~~~
sudo apt-get install g++ cmake gfortran libblas-dev
sudo pip install pytest pep8
~~~
Various (different) CI servers are equipped with different software versions. Let us try them.

Comments please ?

**Comment by bast** [comment]
For the moment we will keep only Travis and Appveyor in the central repo since these services are free and mainstream. More services would dilute our (my) focus too much and IMO offer little bonus for this project. Of course nothing speaks against using more CI services on your fork.
