### ISSUE TITLE
Missing documentation...

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#40]
I am just missing documentation 
https://autocmake.readthedocs.org/en/latest/developers/configuration.html
according to comment in autocmake.cfg:
~~~
# CMakeLists.txt and setup.py will be generated from this file
# see: http://autocmake.readthedocs.org/en/latest/developers/configuration.html
~~~

**Comment by bast** [comment]
It's work in progress. I was waiting with this because I wasn't sure about the configuration options. But now that it stabilized a bit it is time to document it.

**Comment by bast** [comment]
I am closing this issue. This is work in progress and the work has started.
Will continue on this the following days.
