### ISSUE TITLE
Adapting and parsing autocmake.cfg in my new project

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#41]
Hi,

in my new project, https://github.com/miroi/fortran_input_reader

the autocmake.cfg is
https://github.com/miroi/fortran_input_reader/blob/master/cmake/autocmake.cfg

What is wrong with the parsing ?

~~~
milias@login.grid.umb.sk:~/Work/qch/software/software_projects/fortran_input_reader_devel/fortran_input_reader/cmake/.python update.py ..
- parsing autocmake.cfg
- assembling modules: [                              ] (0/10)Traceback (most recent call last):
  File "update.py", line 464, in <module>
    main(sys.argv)
  File "update.py", line 355, in main
    modules = fetch_modules(config, relative_path)
  File "update.py", line 273, in fetch_modules
    config_docopt, config_define, config_export, config_fetch = parse_cmake_module(f.read())
  File "update.py", line 396, in parse_cmake_module
    autocmake_entry = '\n'.join(s_out).split('autocmake.cfg configuration::')[1]
IndexError: list index out of range
~~~

**Comment by bast** [comment]
Basically you can remove everything except the "source" lines.
Also you don't need both `fc` and `fc_optional`. If you want Fortran support to
be optional, take the latter, otherwise the former.
The `fc_optional` was introduced for C/C++ project which
offer optional Fortran interface.

**Comment by bast** [comment]
Example: https://github.com/bast/numgrid/blob/master/cmake/autocmake.cfg

**Comment by miroi** [comment]
Fine, thanks, I took and adapted that autocmake.cfg file.

I also removed googletest as this requires external sources.
~~~
Scanning dependencies of target googletest
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[2]: Warning: File `CMakeFiles/googletest.dir/flags.make' has modification time 19 s in the future
make[2]: *** No rule to make target `../external/googletest/src/gtest-all.cc', needed by `CMakeFiles/googletest.dir/external/googletest/src/gtest-all.cc.o'.  Stop.
make[1]: *** [CMakeFiles/googletest.dir/all] Error 2
make: *** [all] Error 2
~~~

Closing this ticket.

**Comment by bast** [comment]
The googletest module is anyway not interesting for a Fortran project.
Documentation for `autocmake.cfg` will come in the following days.
