### ISSUE TITLE
internal tests

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#5]
Hi Rado,

please how to make internal tests compiled and ran ? The test.py script somehow does not this. Some documentation would help.

```
milias@login.grid.umb.sk:~/Work/qch/software/autocmake_devel/autocmake_miroi_fork/test/.python test.py -h        
milias@login.grid.umb.sk:~/Work/qch/software/autocmake_devel/autocmake_miroi_fork/test/.python test.py --help
milias@login.grid.umb.sk:~/Work/qch/software/autocmake_devel/autocmake_miroi_fork/test/.

lias@frpd2.pd.uniza.sk:~/Work/qch/qch_software/autocmake_devel/autocmake/test/.python test.py 
ilias@frpd2.pd.uniza.sk:~/Work/qch/qch_software/autocmake_devel/autocmake/test/.ls cxx/
cmake/	src/
ilias@frpd2.pd.uniza.sk:~/Work/qch/qch_software/autocmake_devel/autocmake/test/.ls cxx/cmake/
autocmake.cfg


```

**Comment by bast** [comment]
The correct way to run the tests is ``py.test test.py``.
See also the [Travis build and test recipe](https://github.com/scisoft/autocmake/blob/master/.travis.yml).
I agree that this should be mentioned in the documentation for developers
of the library. I will keep the issue open until this is done.
