### ISSUE TITLE
Other tests for MPI, OpenMP, GPU...

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#57]
Would be good to add some simple tests checking OpenMPI, OpenMP, GPU stuff.

**Comment by bast** [comment]
It is possible to test MPI on Travis. It is probably possible to test OpenMP.
I don't know how that works on Appveyor.
However these are modules which are difficult to get wrong or break
and I wonder whether we will win by increasing the complexity of the testing.
For the moment I would stay away from GPU.

**Comment by bast** [comment]
I am closing this issue. MPI test is there. I have nothing against OpenMP. I don't know
how easy it is to test GPU integration on Travis but anyway we currently have no GPU modules in the library. This issue is also a bit too wide to wait to be closed with commits.
