### ISSUE TITLE
One test for checking math libs internal paralelization

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#58]
Hi,
hereby I advocate for "bigger" fc_lapack_blas test for checking/employing/measuring  the internal OpenMP paralelization of selected math libraries (MKL, ESSL, OpenBLAS, Atlas?, ACML?).

The test's executable would accept one parameter (let say  n - size of the matrix problem), the user would set up OpenMP environmental variables for the math library and lauch the process on his machine. Based on measured (printed) timings he would see how good is the math lib parallelization. (In DIRAC we have this with MKL library).

**Comment by bast** [comment]
This is an interesting question but I would study this in a separate project.
I think this is far beyond the scope of this library. I would not bake this into Autocmake.

**Comment by miroi** [comment]
Good, I agree. This is more suitable for a separate, autocmake-enhanced project.
