### ISSUE TITLE
Python 2.6.2 and update.py on IBM AIX

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#69]
Hi,

would it be please possible to adapt *update.py* for Python version 2.6.2 ? This is IBM AIX machine, and if not, I would have to disturb admin concerning low Python version.

~~~
ilias@147.213.80.175:~/work/qch/software/mathlibs-tester/cmake/.uname -a
AIX f01c10n02 1 7 00CFA0664C00 powerpc unknown AIX
ilias@147.213.80.175:~/work/qch/software/mathlibs-tester/cmake/.python -V               
Python 2.6.2
ilias@147.213.80.175:~/work/qch/software/mathlibs-tester/cmake/.python update.py  --self
Traceback (most recent call last):
  File "update.py", line 5, in <module>
    from collections import OrderedDict, namedtuple
ImportError: cannot import name OrderedDict
ilias@147.213.80.175:~/work/qch/software/mathlibs-tester/cmake/.python update.py ..     
Traceback (most recent call last):
  File "update.py", line 5, in <module>
    from collections import OrderedDict, namedtuple
ImportError: cannot import name OrderedDict
ilias@147.213.80.175:~/work/qch/software/mathlibs-tester/cmake/.
~~~

**Comment by bast** [comment]
OrderedDict can be substituted with the following backport:
http://code.activestate.com/recipes/576693/
But instead of bloating our code I think the better solution is to disturb the admin and/or to use Virtualenv
and do a `pip install ordereddict`.

**Comment by bast** [comment]
I really don't want to backport the code. This functionality is only relevant for developers and I believe that
developers can assure they have a Python version that supports OrderedDict. Closing.
