### ISSUE TITLE
switch off email notification in travis-ci

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#70]
Could you please switch off email notification for travis-ci ? I am flooded with email, it's sufficient to check tests status on the web.

http://docs.travis-ci.com/user/notifications/#Email-notifications

**Comment by bast** [comment]
Strange. I am not getting any emails from Travis. Never got one although I have a number of projects
on Travis.

**Comment by miroi** [comment]
Here is the probable reason: http://docs.travis-ci.com/user/notifications/#I%E2%80%99m-not-receiving-any-build-notifications

I am flooded with emails, and I am seeking to stop that flow from travis-ci.

**Comment by bast** [comment]
My email addresses are registered and verified. If you know how to stop the emails, please go ahead.
