### ISSUE TITLE
More tests combinations

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#76]
Hi,
would it be worth to set up more blas/lapack tests combinations  for CI service(s) ? 
This is gfortran <> system_native/atlas/openblas/acml <> dynamic/static (the free of charge acml library is available after downloading by the yml-script).

Here I have tests combinations in my new project, which are also on CDash:
https://github.com/miroi/mathlibs-tester/blob/master/cdash_scripts/hpcc_umb_runtest.bash

This task would require IMO adding next CI service into autocmake. The best one, as I checked, seems to be the circleci, which is also very fast. The main reason is that each CI service is operating on different virtual Linux architecture, and there might be some conflicts in packages on older architectures (like I found with travis-ci https://github.com/scisoft/autocmake/issues/51#issuecomment-127579836 ). In such a case to enable to pass tests, the defined MATH_LIB_SEARCH_ORDER would ensure working library linked. For example, for the MATH_LIB_SEARCH_ORDER='OPENBLAS;ATLAS;SYSTEM_NATIVE;ACML' setting  the tests will pass at least with one math-library package installed.

One would have to play with Linux packages for (OPENBLAS;ATLAS;SYSTEM_NATIVE;ACML)-dynamic/static linking combinations to settle all lapack/blas tests properly in travis-ci and circle-ci. The number of unique compiler-library-linking tests should be 16 (8 for blas,8 for lapack), without integer*8. However, if some modern free library would provide ILP64 data model, then the total number of tests will be higher.

PS1: The ACML library has 64-bit integer mode, see http://developer.amd.com/tools-and-sdks/archive/amd-core-math-library-acml/acml-downloads-resources/ . This means 4 more combinations.

PS2: I am thinking now(17.8.2015) of more CI tests which would skip the *py.test test/test.py* layer and do own buildup on selected tests, mainly math tests with various libraries.  But if all such above mentioned combinations could be done safely through the *test.py* script, than there is no need for such solution.

**Comment by bast** [comment]
I would for the moment like to stay with Travis/Appveyor and test.py and keep things as simple as possible.

**Comment by miroi** [comment]
OK; than we can "pack" more math-libraries tests into test.py/travis-ci/appveyour based on the   MATH_LIB_SEARCH_ORDER. Probably we do not exhaust all free math-libs combinations due to possible conflicts between some installed packages, but we can test as many cmake library detections as possible.

**Comment by bast** [comment]
I would perhaps wait until we split the math library module. Then not only the code gets simpler but also the testing.

**Comment by miroi** [comment]
Good idea.

**Comment by bast** [comment]
Closing this issue.
