### ISSUE TITLE
How to deal with autocmake files in user's project ?

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#8]
Hi,
finally I adapted the autocmake for building my simple (github) project.  

Should autocmake-user include all autocmake's files into his project's repository ? What is the recommended approach ?  The "cmake/" directory and the setup.py script are more-less stable (as "pure" autocmake stuff), only the CMakeLists.txt undergoes heavy changes.

Because all important files are in the "cmake/" directory, maybe on should version only the "cmake/" folder ?

```
milias@login.grid.umb.sk:~/Work/qch/software/autocmake_devel/sec_quant_F90_autocmake/.git status 
# On branch autocmake
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	CMakeLists.txt
#	cmake/
#	setup.py
nothing added to commit but untracked files present (use "git add" to track)
milias@login.grid.umb.sk:~/Work/qch/software/autocmake_devel/sec_quant_F90_autocmake/.
```

**Comment by bast** [comment]
What I do is to include/track all generated files. The reason for this is that when
you distribute your code to users/colleagues you probably don't want them to go through
the Autocmake steps but they will run ``setup.py`` directly and expect everything to just work (TM).
Ideally the end-user does not have to run any Autocmake scripts.

**Comment by miroi** [comment]
Fine, good approach - versioning all autocmake's generated files and leaning on setup.py only.

Your answer could go into the documentation (into FAQs ?), after one could close this issue.

**Comment by bast** [comment]
I agree. This should go to FAQs.
