### ISSUE TITLE
Missing set the cmake command flag

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#81]
Hi,

on one of our SIVVP.sk clusters (more precisely, it's hpc.uniza.sk) we have cmake 2.6 as the default (/usr/bin/cmake); and the newer cmake is called as /usr/bin/cmake28.

Autocmake can not take the */usr/bin/cmake28*, and the default cmake of version 2.6 is not acceptable.

I am missing this flag which is present in DIRAC  setup:
~~~
  --cmake STRING        set the cmake command [default: cmake; e.g. --cmake
                        cmake28]
~~~
Any help, plase ?

**Comment by bast** [comment]
Can't this problem be solved by (re)setting `$PATH`?

**Comment by miroi** [comment]
The problem is here:
https://github.com/scisoft/autocmake/blob/master/update.py#L95

The generated setup.py script accepts only the "pure" cmake command, no *cmake28*.

**Comment by bast** [comment]
Yes. But why can't this be solved by exporting `PATH=/some/other/cmake1234/bin:$PATH`?

**Comment by miroi** [comment]
I don't see the *pure* 2.8 cmake binary on that cluster.

I see 
~~~
umbilias@login.hpc.uniza.sk:~/work/software/mathlibs-tester/.ls -l /usr/bin/cmake28
-rwxr-xr-x 1 root root 3535936 Mar  4  2013 /usr/bin/cmake28*
~~~
and associated files:
~~~
umbilias@login.hpc.uniza.sk:~/work/software/mathlibs-tester/.ls -l /usr/share/cmake28/
total 36
drwxr-xr-x 8 root root 20480 Jun 13  2013 Modules/
drwxr-xr-x 2 root root  4096 Jun 13  2013 Templates/
drwxr-xr-x 2 root root  4096 Jun 13  2013 completions/
drwxr-xr-x 4 root root  4096 Jun 13  2013 editors/
drwxr-xr-x 2 root root  4096 Jun 13  2013 include/
umbilias@login.hpc.uniza.sk:~/work/software/mathlibs-tester/.
~~~
Where can I find the complete package, including binaries ?

**Comment by bast** [comment]
Hm. That is an unfortunate setup. It exists on a number of clusters. Probably we then need a way to set an alternative CMake command as you suggest.

**Comment by miroi** [comment]
Hi again,

also similar setting problem on that cluster is with python: the default one,  /usr/bin/python, is of version 2.6.6. There is the newer one, but is as /apps/Python-2.7.8/bin/python2.7 (2.7.8), it means it has to be called as python2.7:
~~~
umbilias@login.hpc.uniza.sk:~/work/software/autocmake/.python2.7 -V
Python 2.7.8
umbilias@login.hpc.uniza.sk:~/work/software/autocmake/.python -V   
Python 2.6.6
~~~

**Comment by bast** [comment]
For the Python problem I highly recommend to use Virtualenv. You can have several venvs, each for a different Python version. It's extremely handy.
