### ISSUE TITLE
git_info.h  gets spoiled with extra strings

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#87]
Hi,
In test/fc_git_info this is the content of  build/*git_info.h*:
~~~
#ifndef GIT_INFO_H_INCLUDED
#define GIT_INFO_H_INCLUDED

#define GIT_COMMIT_HASH "b47f27c"
#define GIT_COMMIT_AUTHOR "Miro Ilia<C5><A1>"
#define GIT_COMMIT_DATE "Mon Aug 24 16:12:38 2015 +0200

    close issue #64
    
    - to fix https://github.com/scisoft/autocmake/issues/64#issuecomment-1313"
#define GIT_BRANCH "patch-6"

#endif /* GIT_INFO_H_INCLUDED */
~~~

The GIT_COMMIT_DATE brings more than one line - it takes the whole commit message. The responsible cmake module should be fixed.

**Comment by bast** [comment]
I cannot reproduce this but I suspect that the REGEX here is too greedy
on your machine:
https://github.com/scisoft/autocmake/blob/master/modules/git_info/git_info_sub.cmake#L36

**Comment by bast** [comment]
Can you please try to debug it on your machine?
Also please see the encoding problem with your Author name.

**Comment by bast** [comment]
Is this problem still relevant? If yes, which CMake version are we talking about?

**Comment by miroi** [comment]
So far I haven't met this problem, so I am closing this issue.  

If I would meet the problem again, I shall reopen this issue.
