### ISSUE TITLE
"python update.py .." is overwriting ../CMakeLists.txt

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#9]
Hi,

the "python update.py .." command is overwriting existing ../CMakeLists.txt buildup receipe.
When I modify autoconf.py and run "update.py ..", I lost the CMakeLists.txt.  Could there be this file's backup before updating it  ?

**Comment by bast** [comment]
We may consider adding a guard against overwriting ``CMakeLists.txt`` and ``setup.py``.
But I don't think this is necessary since both files typically do
not require manual edits and typically do not contain anything that could
not be regenerated.

**Comment by miroi** [comment]
Hi, 

for me, novice in the autocmake project, the setup.py is not needed to be changes. Fortunately, it's "untouchable". 

But I have to change heavily  the CMakeLists.txt - at least put there all source files of the project. So I would suggest backup of the CMakeLists.txt file only, because after each regeneration, I must manually copy stuff from old CMakeLists.txt_manually_saved  into the new, regenerated one.

**Comment by bast** [comment]
You almost never need to edit `CMakeLists.txt` - the preferred way is to specify your sources/libraries
in `src/CMakeLists.txt` and include it using [src.cmake](https://github.com/scisoft/autocmake/blob/master/modules/src.cmake).
If you need more customization, then create custom CMake files and include
them via `autocmake.cfg`.

**Comment by miroi** [comment]
Aaaah....I (manually) copied all entries from the documentation web into my cmake/automake.cfg, but I haven't seen  automake.cfg input for the https://autocmake.readthedocs.org/en/latest/module-reference.html#src-cmake . 

I put 
'''
[source]
source: https://github.com/scisoft/autocmake/raw/master/modules/src.cmake
'''
into automake.cfg  and it seems to be working. Is it OK so ?

**Comment by bast** [comment]
Yes, that's currently the way to do it. We need to improve the doc - work in progress.
