### ISSUE TITLE
Tests also for cblas/clapack detection ?

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#95]
We have Fortran tests for blas/lapack. Shouldn't we add analogous tests for "\<clapack.h\>", "\<cblas.h\>"
  ? Would be good to verify proper autocmake's detection of C-blas/lapack librares.

**Comment by bast** [comment]
I guess it would be good. But rather than baking it into `math_libs.cmake` we should IMO
split that module and create isolated `cblas` and `clapack` modules and then also test those.

**Comment by miroi** [comment]
Fine. First I would try to make a very simple *cc_cblas* test without touching math_libs.cmake. I assume (hope) that the *math_libs.cmake* detection works also with the C language in the same way as it works with Fortran.

**Comment by bast** [comment]
Sure just go ahead.
